### ISSUE TITLE
Setting up software on Ubuntu 18.04

### ISSUE THREAD

**Issue by lesliewubbel** [OpenVessel/OpenVesselPublic#1]
```
   Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).


    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rjeg9dxh/psycopg2/`

```
when I run the pip install requirements command 

pip install -r requirements on Linux

**Comment by lesliewubbel** [comment]
Fastest solution is this remove the  psycopg2 from the install requirements 

If you are installing psycopg2 from a requirements.txt file, you can comment out the package listed in the file as:

# psycopg2==2.6.2
Then install the package as suggested above, then install other requirements from the file with the package name still commented.

https://web.archive.org/web/20140615091953/http://goshawknest.wordpress.com/2011/02/16/how-to-install-psycopg2-under-virtualenv/

**Comment by lesliewubbel** [comment]
Fix was `sudo apt-get install libpq-dev python-dev`

**Comment by lesliewubbel** [comment]
```
Could not find a version that satisfies the requirement vtk==9.0.1 (from -r requirements.txt (line 89)) (from versions: 8.0.0.dev20170717, 8.1.0, 8.1.1, 8.1.2)
No matching distribution found for vtk==9.0.1 (from -r requirements.txt (line 89))
```

MAKE PERMANENT CHANGES TO VTK python package to `vtk==8.1.2`

**Comment by lesliewubbel** [comment]
**start repeats with many packages** 

 error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for alembic
  Running setup.py clean for alembic
  Running setup.py bdist_wheel for antiorm ... error
  Complete output from command /root/vessel_env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vjphxeyo/antiorm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp8luynlsopip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for antiorm
  Running setup.py clean for antiorm
  Running setup.py bdist_wheel for blinker ... error
  Complete output from command /root/vessel_env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vjphxeyo/blinker/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpay40l47kpip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'


**end of error** 

`Command "/root/vessel_env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vjphxeyo/gevent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8jlbeqbz-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/vessel_env/include/site/python3.6/gevent" failed with error code 1 in /tmp/pip-build-vjphxeyo/gevent/`


**Solution** 

`pip3 install wheel`

```
sudo apt-get install python3 python-dev python3-dev \
     build-essential libssl-dev libffi-dev \
     libxml2-dev libxslt1-dev zlib1g-dev \
     python-pip
```

**Comment by lesliewubbel** [comment]
```
Traceback (most recent call last):
  File "/root/vessel_env/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/root/vessel_env/lib/python3.6/site-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/root/vessel_env/lib/python3.6/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/root/vessel_env/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/vessel_env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/vessel_env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/vessel_env/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/vessel_env/lib/python3.6/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/root/vessel_env/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/vessel_env/lib/python3.6/site-packages/flask/cli.py", line 860, in run_command
    extra_files=extra_files,
  File "/root/vessel_env/lib/python3.6/site-packages/werkzeug/serving.py", line 1012, in run_simple
    inner()
  File "/root/vessel_env/lib/python3.6/site-packages/werkzeug/serving.py", line 965, in inner
    fd=fd,
  File "/root/vessel_env/lib/python3.6/site-packages/werkzeug/serving.py", line 808, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/root/vessel_env/lib/python3.6/site-packages/werkzeug/serving.py", line 701, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by lesliewubbel** [comment]
VTK on Ubuntu, the main cause to be due to 'virtual memory exhausted: Cannot allocate memory'

at step sudo make -j 
```

make[1]: *** [ThirdParty/freetype/vtkfreetype/CMakeFiles/freetype.dir/all] Interrupt
CMakeFiles/Makefile2:16471: recipe for target 'ThirdParty/libproj/vtklibproj/src/CMakeFiles/libproj.dir/all' failed
make[1]: *** [ThirdParty/libproj/vtklibproj/src/CMakeFiles/libproj.dir/all] Interrupt
make[2]: *** Deleting file 'ThirdParty/lzma/vtklzma/CMakeFiles/lzma.dir/src/liblzma/lzma/lzma_decoder.c.o'
ThirdParty/lzma/vtklzma/CMakeFiles/lzma.dir/build.make:797: recipe for target 'ThirdParty/lzma/vtklzma/CMakeFiles/lzma.dir/src/liblzma/lzma/lzma_decoder.c.o' failed
make[2]: *** [ThirdParty/lzma/vtklzma/CMakeFiles/lzma.dir/src/liblzma/lzma/lzma_decoder.c.o] Interrupt
CMakeFiles/Makefile2:10792: recipe for target 'ThirdParty/lzma/vtklzma/CMakeFiles/lzma.dir/all' failed
make[1]: *** [ThirdParty/lzma/vtklzma/CMakeFiles/lzma.dir/all] Interrupt
Makefile:160: recipe for target 'all' failed
make: *** [all] Interrupt
```


` from shared object
make[2]: fork: Cannot allocate memory
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
ThirdParty/hdf5/vtkhdf5/src/CMakeFiles/vtkhdf5_src.dir/build.make:670: recipe for target 'ThirdParty/hdf5/vtkhdf5/src/CMakeFiles/vtkhdf5_src.dir/H5Dbtree2.c.o' failed
make[2]: *** [ThirdParty/hdf5/vtkhdf5/src/CMakeFiles/vtkhdf5_src.dir/H5Dbtree2.c.o] Error 1
make[2]: *** Waiting for unfinished jobs..`

```

Common/Core/CMakeFiles/CommonCore.dir/build.make:581: recipe for target 'Common/Core/CMakeFiles/CommonCore.dir/vtkDataArray.cxx.o' failed
virtual memory exhausted: Cannot allocate memory
make[2]: *** [Common/Core/CMakeFiles/CommonCore.dir/vtkDataArray.cxx.o] Error 4
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** Waiting for unfinished jobs....
Common/Core/CMakeFiles/CommonCore.dir/build.make:243: recipe for target 'Common/Core/CMakeFiles/CommonCore.dir/vtkTypeFloat32Array.cxx.o' failed
make[2]: *** [Common/Core/CMakeFiles/CommonCore.dir/vtkTypeFloat32Array.cxx.o] Error 4
Common/Core/CMakeFiles/CommonCore.dir/build.make:438: recipe for target 'Common/Core/CMakeFiles/CommonCore.dir/vtkBoxMuellerRandomSequence.cxx.o' failed
make[2]: *** [Common/Core/CMakeFiles/CommonCore.dir/vtkBoxMuellerRandomSequence.cxx.o] Error 4
Common/Core/CMakeFiles/CommonCore.dir/build.make:1674: recipe for target 'Common/Core/CMakeFiles/CommonCore.dir/vtkUnsignedLongArray.cxx.o' failed
make[2]: *** [Common/Core/CMakeFiles/CommonCore.dir/vtkUnsignedLongArray.cxx.o] Error 1
```

Resized the volume of lindo to 4GB new error 

```

cc1plus: out of memory allocating 488 bytes after a total of 2494464 bytes

cc1: out of memory allocating 65536 bytes after a total of 4005888 bytes
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory

cc1plus: out of memory allocating 488 bytes after a total of 2363392 bytes
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory

```
```

CMakeFiles/Makefile2:14223: recipe for target 'ThirdParty/theora/vtktheora/CMakeFiles/theora.dir/all' failed
make[1]: *** [ThirdParty/theora/vtktheora/CMakeFiles/theora.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:13765: recipe for target 'ThirdParty/hdf5/vtkhdf5/src/CMakeFiles/vtkhdf5_src.dir/all' failed
make[1]: *** [ThirdParty/hdf5/vtkhdf5/src/CMakeFiles/vtkhdf5_src.dir/all] Error 2
[ 11%] Built target vtkCommonDataModel-hierarchy
CMakeFiles/Makefile2:14880: recipe for target 'ThirdParty/libxml2/vtklibxml2/CMakeFiles/libxml2.dir/all' failed
make[1]: *** [ThirdParty/libxml2/vtklibxml2/CMakeFiles/libxml2.dir/all] Error 2
CMakeFiles/Makefile2:9688: recipe for target 'Common/Core/CMakeFiles/CommonCore.dir/all' failed
make[1]: *** [Common/Core/CMakeFiles/CommonCore.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```
```

cc1plus: out of memory allocating 8032 bytes after a total of 954368 bytes

cc1plus: out of memory allocating 262144 bytes after a total of 1597440 bytes

cc1plus: out of memory allocating 14156 bytes after a total of 1130496 bytes

cc1plus: out of memory allocating 8032 bytes after a total of 929792 bytes
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
Common/DataModel/CMakeFiles/CommonDataModel.dir/build.make:2760: recipe for target 'Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkStaticCellLinks.cxx.o' failed
make[2]: *** [Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkStaticCellLinks.cxx.o] Error 1
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
make[2]: *** Waiting for unfinished jobs....
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Common/DataModel/CMakeFiles/CommonDataModel.dir/build.make:1330: recipe for target 'Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkHyperTreeGrid.cxx.o' failed
make[2]: *** [Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkHyperTreeGrid.cxx.o] Error 1
Common/DataModel/CMakeFiles/CommonDataModel.dir/build.make:3111: recipe for target 'Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkVoxel.cxx.o' failed
make[2]: *** [Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkVoxel.cxx.o] Error 1
Common/DataModel/CMakeFiles/CommonDataModel.dir/build.make:3137: recipe for target 'Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkXMLDataElement.cxx.o' failed
make[2]: *** [Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkXMLDataElement.cxx.o] Error 1
Common/DataModel/CMakeFiles/CommonDataModel.dir/build.make:1759: recipe for target 'Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkKdNode.cxx.o' failed
make[2]: *** [Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkKdNode.cxx.o] Error 1
Common/DataModel/CMakeFiles/CommonDataModel.dir/build.make:2162: recipe for target 'Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkPerlinNoise.cxx.o' failed
make[2]: *** [Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkPerlinNoise.cxx.o] Error 1
Common/DataModel/CMakeFiles/CommonDataModel.dir/build.make:2474: recipe for target 'Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkQuadraticHexahedron.cxx.o' failed
make[2]: *** [Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkQuadraticHexahedron.cxx.o] Error 1
Common/DataModel/CMakeFiles/CommonDataModel.dir/build.make:2903: recipe for target 'Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkTetra.cxx.o' failed
make[2]: *** [Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkTetra.cxx.o] Error 1
Common/DataModel/CMakeFiles/CommonDataModel.dir/build.make:3189: recipe for target 'Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkOverlappingAMR.cxx.o' failed
make[2]: *** [Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkOverlappingAMR.cxx.o] Error 1
Common/DataModel/CMakeFiles/CommonDataModel.dir/build.make:3202: recipe for target 'Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkUniformGridAMR.cxx.o' failed
make[2]: *** [Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkUniformGridAMR.cxx.o] Error 1
Common/DataModel/CMakeFiles/CommonDataModel.dir/build.make:2461: recipe for target 'Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkQuadraticEdge.cxx.o' failed
make[2]: *** [Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkQuadraticEdge.cxx.o] Error 1
Common/DataModel/CMakeFiles/CommonDataModel.dir/build.make:1902: recipe for target 'Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkLocator.cxx.o' failed
make[2]: *** [Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkLocator.cxx.o] Error 1
Utilities/PythonInterpreter/CMakeFiles/PythonInterpreter.dir/build.make:95: recipe for target 'Utilities/PythonInterpreter/CMakeFiles/PythonInterpreter.dir/vtkPythonInterpreter.cxx.o' failed
make[2]: *** [Utilities/PythonInterpreter/CMakeFiles/PythonInterpreter.dir/vtkPythonInterpreter.cxx.o] Error 4
Common/DataModel/CMakeFiles/CommonDataModel.dir/build.make:1317: recipe for target 'Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkHyperTreeCursor.cxx.o' failed
make[2]: *** [Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkHyperTreeCursor.cxx.o] Error 1
Common/DataModel/CMakeFiles/CommonDataModel.dir/build.make:1382: recipe for target 'Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkHyperTreeGridLevelEntry.cxx.o' failed
make[2]: *** [Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkHyperTreeGridLevelEntry.cxx.o] Error 1
CMakeFiles/Makefile2:13523: recipe for target 'Utilities/PythonInterpreter/CMakeFiles/PythonInterpreter.dir/all' failed
make[1]: *** [Utilities/PythonInterpreter/CMakeFiles/PythonInterpreter.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Common/DataModel/CMakeFiles/CommonDataModel.dir/build.make:654: recipe for target 'Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkConvexPointSet.cxx.o' failed
make[2]: *** [Common/DataModel/CMakeFiles/CommonDataModel.dir/vtkConvexPointSet.cxx.o] Error 1

cc1plus: out of memory allocating 32768 bytes after a total of 1503232 bytes

cc1plus: out of memory allocating 262144 bytes after a total of 1499136 bytes
virtual memory exhausted: Cannot allocate memory
/usr/lib/gcc/x86_64-linux-gnu/7/cc1plus: error while loading shared libraries: libc.so.6: failed to map segment from shared object

```
